name: Build and Publishing

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Builder
        run: echo dummy-step

      - name: List packaged files
        run: ls -lhR RPMS/

      - name: Publishing RPM on github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./RPMS/*/*.rpm
